import {
  LayoutDashboard,
  TrendingUp,
  BookOpen,
  Calendar,
  Building2,
  Image as ImageIcon,
  Wrench,
  FileText,
  ClipboardList,
  Receipt,
  Users,
  CheckSquare,
  Bell,
  Clock,
  NotebookPen,
  Package,
  FileStack,
  MessageSquare,
  UserCog,
  Store,
  Tags,
  Globe,
  Inbox,
  ListChecks,
  Star,
  Wallet,
  Stamp,
  MapPin,
  Building,
  BellRing,
  CreditCard,
  ShieldCheck,
  UserCircle,
  HardHat,
  type LucideIcon,
} from "lucide-react";

export const MENU_ICONS: Record<string, LucideIcon> = {
  "/admin": LayoutDashboard,
  "/admin/analytics": TrendingUp,
  "/admin/manual": BookOpen,
  "/admin/calendar": Calendar,
  "/admin/field-management": Building2,
  "/admin/sites": HardHat,
  "/admin/customer-pages": ImageIcon,
  "/admin/as-requests": Wrench,
  "/admin/quotes": FileText,
  "/admin/work-orders": ClipboardList,
  "/admin/transactions": Receipt,
  "/admin/customers": Users,
  "/admin/todos": CheckSquare,
  "/admin/notification-center": Bell,
  "/admin/attendance": Clock,
  "/admin/work-logs": NotebookPen,
  "/admin/materials": Package,
  "/admin/templates": FileStack,
  "/admin/quick-phrases": MessageSquare,
  "/admin/employees": UserCog,
  "/admin/vendors": Store,
  "/admin/categories": Tags,
  "/admin/site-management": Globe,
  "/admin/inquiries": Inbox,
  "/admin/portfolio": ImageIcon,
  "/admin/process": ListChecks,
  "/admin/reviews": Star,
  "/admin/finance": Wallet,
  "/admin/approvals": Stamp,
  "/admin/work-sites": MapPin,
  "/admin/company-settings": Building,
  "/admin/notifications": BellRing,
  "/admin/billing": CreditCard,
  "/admin/team-permissions": ShieldCheck,
  "/admin/settings": UserCircle,
};
